version: "3"

services:
    nginx:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
            args:
                - GOOGLE_ANALYTICS_GTAG=$GOOGLE_ANALYTICS_GTAG
                - GOOGLE_RECAPTCHA_SITE_KEY=$GOOGLE_RECAPTCHA_SITE_KEY
        image: swotnginx
        ports:
            - 80:80
        depends_on:
            - backend
    backend:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile
        image: swotbackend
        expose:
            - 3000
        command: "npm start"
