version: "3"

services:
    nginx:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/nginx/dev/Dockerfile
        ports:
            - 80:80
        volumes:
            - ./docker/nginx:/etc/nginx/conf.d
            - ./client/public:/usr/share/nginx/html
        depends_on:
            - backend
    backend:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile
        volumes:
            - .:/app
        expose:
            - 3000
    watcher:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/watcher/Dockerfile
        volumes:
            - ./client:/app/client
