# The second stage
# Copy React static files and start nginx
FROM nginx:stable-alpine
ARG AZURE_STORAGE_ACCOUNT
COPY ./docker/nginx/dev.conf.template /etc/nginx/conf.d/

# Generate NGINX Conf by substituting environment variables
RUN envsubst '${AZURE_STORAGE_ACCOUNT}' < /etc/nginx/conf.d/dev.conf.template > /etc/nginx/conf.d/default.conf
RUN rm /etc/nginx/conf.d/dev.conf.template

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
